//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 05.06.2011 16:27:17
namespace CapgeminiSurface.ConferenceDataService
{
    
    /// <summary>
    /// There are no comments for NdcAgendaContainer in the schema.
    /// </summary>
    public partial class NdcAgendaContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NdcAgendaContainer object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NdcAgendaContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("NdcAgenda", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("CapgeminiSurface.ConferenceDataService", typeName.Substring(9)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CapgeminiSurface.ConferenceDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("NdcAgenda.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Session> Sessions
        {
            get
            {
                if ((this._Sessions == null))
                {
                    this._Sessions = base.CreateQuery<Session>("Sessions");
                }
                return this._Sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Session> _Sessions;
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Speaker> Speakers
        {
            get
            {
                if ((this._Speakers == null))
                {
                    this._Speakers = base.CreateQuery<Speaker>("Speakers");
                }
                return this._Speakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Speaker> _Speakers;
        /// <summary>
        /// There are no comments for Agendas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Agenda> Agendas
        {
            get
            {
                if ((this._Agendas == null))
                {
                    this._Agendas = base.CreateQuery<Agenda>("Agendas");
                }
                return this._Agendas;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Agenda> _Agendas;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSpeakers(Speaker speaker)
        {
            base.AddObject("Speakers", speaker);
        }
        /// <summary>
        /// There are no comments for Agendas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAgendas(Agenda agenda)
        {
            base.AddObject("Agendas", agenda);
        }
    }
    /// <summary>
    /// There are no comments for NdcAgenda.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Session
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="startHour">Initial value of StartHour.</param>
        /// <param name="durationInMinutes">Initial value of DurationInMinutes.</param>
        /// <param name="day">Initial value of Day.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="agendaId">Initial value of AgendaId.</param>
        /// <param name="track">Initial value of Track.</param>
        /// <param name="startMinute">Initial value of StartMinute.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Session CreateSession(int ID, string title, int startHour, int durationInMinutes, int day, string description, int agendaId, int track, int startMinute)
        {
            Session session = new Session();
            session.Id = ID;
            session.Title = title;
            session.StartHour = startHour;
            session.DurationInMinutes = durationInMinutes;
            session.Day = day;
            session.Description = description;
            session.AgendaId = agendaId;
            session.Track = track;
            session.StartMinute = startMinute;
            return session;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property StartHour in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StartHour
        {
            get
            {
                return this._StartHour;
            }
            set
            {
                this.OnStartHourChanging(value);
                this._StartHour = value;
                this.OnStartHourChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StartHour;
        partial void OnStartHourChanging(int value);
        partial void OnStartHourChanged();
        /// <summary>
        /// There are no comments for Property DurationInMinutes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DurationInMinutes
        {
            get
            {
                return this._DurationInMinutes;
            }
            set
            {
                this.OnDurationInMinutesChanging(value);
                this._DurationInMinutes = value;
                this.OnDurationInMinutesChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DurationInMinutes;
        partial void OnDurationInMinutesChanging(int value);
        partial void OnDurationInMinutesChanged();
        /// <summary>
        /// There are no comments for Property Day in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Day
        {
            get
            {
                return this._Day;
            }
            set
            {
                this.OnDayChanging(value);
                this._Day = value;
                this.OnDayChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Day;
        partial void OnDayChanging(int value);
        partial void OnDayChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property AgendaId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AgendaId
        {
            get
            {
                return this._AgendaId;
            }
            set
            {
                this.OnAgendaIdChanging(value);
                this._AgendaId = value;
                this.OnAgendaIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AgendaId;
        partial void OnAgendaIdChanging(int value);
        partial void OnAgendaIdChanged();
        /// <summary>
        /// There are no comments for Property Track in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Track
        {
            get
            {
                return this._Track;
            }
            set
            {
                this.OnTrackChanging(value);
                this._Track = value;
                this.OnTrackChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Track;
        partial void OnTrackChanging(int value);
        partial void OnTrackChanged();
        /// <summary>
        /// There are no comments for Property StartMinute in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StartMinute
        {
            get
            {
                return this._StartMinute;
            }
            set
            {
                this.OnStartMinuteChanging(value);
                this._StartMinute = value;
                this.OnStartMinuteChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StartMinute;
        partial void OnStartMinuteChanging(int value);
        partial void OnStartMinuteChanged();
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                if ((value != null))
                {
                    this._Speakers = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Speaker> _Speakers = new global::System.Collections.ObjectModel.Collection<Speaker>();
        /// <summary>
        /// There are no comments for Agenda in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Agenda Agenda
        {
            get
            {
                return this._Agenda;
            }
            set
            {
                this._Agenda = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Agenda _Agenda;
    }
    /// <summary>
    /// There are no comments for NdcAgenda.Speaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Speaker
    {
        /// <summary>
        /// Create a new Speaker object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="bio">Initial value of Bio.</param>
        /// <param name="agendaId">Initial value of AgendaId.</param>
        /// <param name="photoUrl">Initial value of PhotoUrl.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Speaker CreateSpeaker(int ID, string name, string bio, int agendaId, string photoUrl)
        {
            Speaker speaker = new Speaker();
            speaker.Id = ID;
            speaker.Name = name;
            speaker.Bio = bio;
            speaker.AgendaId = agendaId;
            speaker.PhotoUrl = photoUrl;
            return speaker;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Bio in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bio
        {
            get
            {
                return this._Bio;
            }
            set
            {
                this.OnBioChanging(value);
                this._Bio = value;
                this.OnBioChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bio;
        partial void OnBioChanging(string value);
        partial void OnBioChanged();
        /// <summary>
        /// There are no comments for Property AgendaId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AgendaId
        {
            get
            {
                return this._AgendaId;
            }
            set
            {
                this.OnAgendaIdChanging(value);
                this._AgendaId = value;
                this.OnAgendaIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AgendaId;
        partial void OnAgendaIdChanging(int value);
        partial void OnAgendaIdChanged();
        /// <summary>
        /// There are no comments for Property PhotoUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhotoUrl
        {
            get
            {
                return this._PhotoUrl;
            }
            set
            {
                this.OnPhotoUrlChanging(value);
                this._PhotoUrl = value;
                this.OnPhotoUrlChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhotoUrl;
        partial void OnPhotoUrlChanging(string value);
        partial void OnPhotoUrlChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                if ((value != null))
                {
                    this._Sessions = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Session> _Sessions = new global::System.Collections.ObjectModel.Collection<Session>();
        /// <summary>
        /// There are no comments for Agenda in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Agenda Agenda
        {
            get
            {
                return this._Agenda;
            }
            set
            {
                this._Agenda = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Agenda _Agenda;
    }
    /// <summary>
    /// There are no comments for NdcAgenda.Agenda in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Agenda
    {
        /// <summary>
        /// Create a new Agenda object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="agendaId">Initial value of AgendaId.</param>
        /// <param name="lastUpdated">Initial value of LastUpdated.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Agenda CreateAgenda(int ID, int version, string title, string agendaId, global::System.DateTime lastUpdated)
        {
            Agenda agenda = new Agenda();
            agenda.Id = ID;
            agenda.Version = version;
            agenda.Title = title;
            agenda.AgendaId = agendaId;
            agenda.LastUpdated = lastUpdated;
            return agenda;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property AgendaId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AgendaId
        {
            get
            {
                return this._AgendaId;
            }
            set
            {
                this.OnAgendaIdChanging(value);
                this._AgendaId = value;
                this.OnAgendaIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AgendaId;
        partial void OnAgendaIdChanging(string value);
        partial void OnAgendaIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdated in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return this._LastUpdated;
            }
            set
            {
                this.OnLastUpdatedChanging(value);
                this._LastUpdated = value;
                this.OnLastUpdatedChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                if ((value != null))
                {
                    this._Sessions = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Session> _Sessions = new global::System.Collections.ObjectModel.Collection<Session>();
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                if ((value != null))
                {
                    this._Speakers = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Speaker> _Speakers = new global::System.Collections.ObjectModel.Collection<Speaker>();
    }
}
